#%Module1.0

#####################################################
proc ModulesHelp { } { 
  global version modroot

  puts stderr "Sets the Environment for Catapult"
}

module-whatis   "Sets the environment for using Catapult (e.g. Catapult)"

module load base/1.0
module load catapult/2024.2_1
module load questa/2021.4
module load verdi/latest
module load vcs/latest
module load dc_shell/T-2022.03-SP4

set repo [getenv REPO_TOP]
prepend-path LD_LIBRARY_PATH ${repo}/lab1/hls/cmod/include:${repo}/include/boost/lib:/cad/mentor/2024.2_1/Mgc_home/shared/lib:/cad/synopsys/vcs_gnu_package/S-2021.09/gnu_9/linux 