#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

SETUP_ORDER = ["single_die", "dual_die_naive", "dual_die_optimized"]
KERNEL_ORDER = ["qkv_proj", "attention", "mlp", "rmsnorm", "out_proj"]
COLORS = {
    "single_die": "#1f77b4",
    "dual_die_naive": "#ff7f0e",
    "dual_die_optimized": "#2ca02c",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot single-die vs dual-die kernel study results from metrics.csv."
    )
    parser.add_argument(
        "--metrics-csv",
        type=Path,
        required=True,
        help="Path to metrics.csv generated by scripts/run_kernel_study.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results/plots"),
        help="Output directory for PNG plots.",
    )
    parser.add_argument(
        "--prefix",
        default="kernel_study",
        help="Filename prefix for generated plots.",
    )
    return parser.parse_args()


def _metric_plot(df: pd.DataFrame, seqs: list[int], metric: str, ylabel: str, out_path: Path) -> None:
    fig, axes = plt.subplots(1, len(seqs), figsize=(7 * len(seqs), 5), constrained_layout=True)
    if len(seqs) == 1:
        axes = [axes]
    width = 0.22
    x = np.arange(len(KERNEL_ORDER))

    for ax, seq in zip(axes, seqs):
        sub = df[df["seq_len"] == seq]
        for i, setup in enumerate(SETUP_ORDER):
            vals = []
            for kernel in KERNEL_ORDER:
                row = sub[(sub["kernel"] == kernel) & (sub["setup"] == setup)]
                vals.append(float(row.iloc[0][metric]))
            ax.bar(x + (i - 1) * width, vals, width=width, label=setup, color=COLORS[setup])
        ax.set_title(f"seq_len={seq}")
        ax.set_xticks(x)
        ax.set_xticklabels(KERNEL_ORDER, rotation=20, ha="right")
        ax.set_ylabel(ylabel)
        ax.grid(axis="y", alpha=0.25)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, ncols=3, loc="upper center", bbox_to_anchor=(0.5, 1.04))
    fig.suptitle(f"Kernel Study: {metric}", y=1.08)
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def _speedup_plot(df: pd.DataFrame, seqs: list[int], out_path: Path) -> None:
    labels: list[str] = []
    naive_ratios: list[float] = []
    optimized_ratios: list[float] = []

    for seq in seqs:
        sub = df[df["seq_len"] == seq]
        for kernel in KERNEL_ORDER:
            single = float(
                sub[(sub["kernel"] == kernel) & (sub["setup"] == "single_die")].iloc[0][
                    "latency_ms_p50"
                ]
            )
            dual_naive = float(
                sub[(sub["kernel"] == kernel) & (sub["setup"] == "dual_die_naive")].iloc[0][
                    "latency_ms_p50"
                ]
            )
            dual_opt = float(
                sub[(sub["kernel"] == kernel) & (sub["setup"] == "dual_die_optimized")].iloc[0][
                    "latency_ms_p50"
                ]
            )
            labels.append(f"{kernel}\nS={seq}")
            naive_ratios.append(single / dual_naive if dual_naive > 0 else 0.0)
            optimized_ratios.append(single / dual_opt if dual_opt > 0 else 0.0)

    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(12, 5), constrained_layout=True)
    ax.bar(x - width / 2, naive_ratios, width=width, color=COLORS["dual_die_naive"], label="single/dual_naive")
    ax.bar(
        x + width / 2,
        optimized_ratios,
        width=width,
        color=COLORS["dual_die_optimized"],
        label="single/dual_optimized",
    )
    ax.axhline(1.0, color="black", linewidth=1, linestyle="--")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=25, ha="right")
    ax.set_ylabel("Latency ratio (>1 means dual setup is faster)")
    ax.set_title("Single-vs-Dual Latency Ratio by Kernel/Sequence")
    ax.grid(axis="y", alpha=0.25)
    ax.legend()
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    args = parse_args()
    if not args.metrics_csv.exists():
        raise SystemExit(f"metrics.csv not found: {args.metrics_csv}")

    df = pd.read_csv(args.metrics_csv)
    seqs = sorted(int(x) for x in df["seq_len"].unique())

    args.out_dir.mkdir(parents=True, exist_ok=True)
    latency_path = args.out_dir / f"{args.prefix}_latency.png"
    throughput_path = args.out_dir / f"{args.prefix}_throughput.png"
    speedup_path = args.out_dir / f"{args.prefix}_speedup.png"

    _metric_plot(
        df=df,
        seqs=seqs,
        metric="latency_ms_p50",
        ylabel="Latency p50 (ms)",
        out_path=latency_path,
    )
    _metric_plot(
        df=df,
        seqs=seqs,
        metric="throughput_tokens_per_s",
        ylabel="Throughput (tokens/s)",
        out_path=throughput_path,
    )
    _speedup_plot(df=df, seqs=seqs, out_path=speedup_path)

    print(latency_path)
    print(throughput_path)
    print(speedup_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
