#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas.errors import EmptyDataError

SETUP_ORDER = ["single_die", "dual_die_tensor_optimized", "dual_die_request_sharded"]
COLORS = {
    "single_die": "#1f77b4",
    "dual_die_tensor_optimized": "#ff7f0e",
    "dual_die_request_sharded": "#2ca02c",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot prefill/decode phase-study outputs from metrics.csv, decode_slo_summary.csv, "
            "and optional kernel_phase_metrics.csv."
        )
    )
    parser.add_argument(
        "--metrics-csv",
        type=Path,
        required=True,
        help="Path to metrics.csv generated by scripts/run_phase_study.py",
    )
    parser.add_argument(
        "--decode-slo-csv",
        type=Path,
        default=None,
        help="Optional path to decode_slo_summary.csv. Defaults to sibling of metrics.csv.",
    )
    parser.add_argument(
        "--kernel-phase-csv",
        type=Path,
        default=None,
        help="Optional path to kernel_phase_metrics.csv. Defaults to sibling of metrics.csv.",
    )
    parser.add_argument(
        "--break-even-csv",
        type=Path,
        default=None,
        help="Optional path to break_even_summary.csv. Defaults to sibling of metrics.csv.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("results/plots"),
        help="Output directory for PNG plots.",
    )
    parser.add_argument(
        "--prefix",
        default="phase_study",
        help="Filename prefix for generated plots.",
    )
    return parser.parse_args()


def _setup_label(name: str) -> str:
    return name.replace("dual_die_", "dual_").replace("_", " ")


def _safe_read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except EmptyDataError:
        return pd.DataFrame()


def _plot_prefill_latency(df: pd.DataFrame, out_path: Path) -> None:
    prefill = df[df["phase"] == "prefill"].copy()
    if prefill.empty:
        return

    prefill = prefill.sort_values(["seq_len", "setup"])
    seqs = sorted(int(x) for x in prefill["seq_len"].unique())

    fig, ax = plt.subplots(figsize=(9, 5), constrained_layout=True)
    for setup in SETUP_ORDER:
        sub = prefill[prefill["setup"] == setup]
        if sub.empty:
            continue
        vals = []
        for seq in seqs:
            row = sub[sub["seq_len"] == seq]
            vals.append(float(row.iloc[0]["latency_ms_p50"]) if not row.empty else np.nan)
        ax.plot(
            seqs,
            vals,
            marker="o",
            linewidth=2,
            color=COLORS[setup],
            label=_setup_label(setup),
        )

    ax.set_title("Prefill p50 Latency vs Sequence Length")
    ax.set_xlabel("Sequence length")
    ax.set_ylabel("Latency p50 (ms)")
    ax.set_xscale("log", base=2)
    ax.grid(alpha=0.25)
    ax.legend()
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def _plot_decode_throughput(df: pd.DataFrame, out_path: Path) -> None:
    decode = df[df["phase"] == "decode"].copy()
    if decode.empty:
        return

    contexts = sorted(int(x) for x in decode["context_len"].unique())
    fig, axes = plt.subplots(1, len(contexts), figsize=(6 * len(contexts), 5), constrained_layout=True)
    if len(contexts) == 1:
        axes = [axes]

    for ax, context in zip(axes, contexts):
        panel = decode[decode["context_len"] == context]
        concurrencies = sorted(int(x) for x in panel["batch"].unique())

        for setup in SETUP_ORDER:
            sub = panel[panel["setup"] == setup]
            if sub.empty:
                continue
            y = []
            for c in concurrencies:
                row = sub[sub["batch"] == c]
                y.append(float(row.iloc[0]["throughput_tokens_per_s"]) if not row.empty else np.nan)
            ax.plot(
                concurrencies,
                y,
                marker="o",
                linewidth=2,
                color=COLORS[setup],
                label=_setup_label(setup),
            )

        ax.set_title(f"decode context={context}")
        ax.set_xlabel("Concurrency")
        ax.set_ylabel("Throughput (tokens/s)")
        ax.grid(alpha=0.25)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, ncols=3, loc="upper center", bbox_to_anchor=(0.5, 1.05))
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def _plot_decode_slo(df: pd.DataFrame, out_path: Path) -> None:
    if df.empty:
        return

    contexts = sorted(int(x) for x in df["context_len"].unique())
    fig, axes = plt.subplots(1, len(contexts), figsize=(6 * len(contexts), 5), constrained_layout=True)
    if len(contexts) == 1:
        axes = [axes]

    width = 0.24

    for ax, context in zip(axes, contexts):
        panel = df[df["context_len"] == context].copy()
        slos = sorted(float(x) for x in panel["slo_ms"].unique())
        x = np.arange(len(slos))

        for idx, setup in enumerate(SETUP_ORDER):
            sub = panel[panel["setup"] == setup]
            y = []
            for slo in slos:
                row = sub[sub["slo_ms"] == slo]
                y.append(float(row.iloc[0]["best_throughput_tokens_per_s"]) if not row.empty else 0.0)
            ax.bar(
                x + (idx - 1) * width,
                y,
                width=width,
                color=COLORS[setup],
                label=_setup_label(setup),
            )

        ax.set_title(f"Throughput @ SLO (context={context})")
        ax.set_xlabel("SLO p90 latency (ms)")
        ax.set_xticks(x)
        ax.set_xticklabels([f"{s:.0f}" if float(s).is_integer() else f"{s:.1f}" for s in slos])
        ax.set_ylabel("Best throughput (tokens/s)")
        ax.grid(axis="y", alpha=0.25)

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, ncols=3, loc="upper center", bbox_to_anchor=(0.5, 1.05))
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def _plot_break_even(df: pd.DataFrame, out_path: Path) -> None:
    if df.empty:
        return

    decode = df[df["phase"] == "decode"].copy()
    if decode.empty:
        return

    decode = decode.sort_values(["context_len", "batch", "setup"])
    labels = [
        f"ctx={int(row.context_len)}\\nC={int(row.batch)}"
        for row in decode.itertuples(index=False)
        if row.setup == "dual_die_tensor_optimized"
    ]
    opt = decode[decode["setup"] == "dual_die_tensor_optimized"]["additional_overlap_needed_ms"].to_numpy()
    shard = decode[decode["setup"] == "dual_die_request_sharded"]["additional_overlap_needed_ms"].to_numpy()

    n = min(len(labels), len(opt), len(shard))
    if n == 0:
        return

    labels = labels[:n]
    opt = opt[:n]
    shard = shard[:n]
    x = np.arange(n)
    width = 0.36

    fig, ax = plt.subplots(figsize=(max(10, n * 0.9), 5), constrained_layout=True)
    ax.bar(x - width / 2, opt, width=width, color=COLORS["dual_die_tensor_optimized"], label="tensor optimized")
    ax.bar(x + width / 2, shard, width=width, color=COLORS["dual_die_request_sharded"], label="request sharded")
    ax.axhline(0.0, color="black", linewidth=1)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.set_ylabel("Additional overlap needed to tie single-die (ms)")
    ax.set_title("Decode Break-Even Gap")
    ax.grid(axis="y", alpha=0.25)
    ax.legend()
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def _plot_kernel_phase_speedup(df: pd.DataFrame, out_path: Path) -> None:
    if df.empty:
        return

    kernels = ["qkv_proj", "attention", "mlp", "rmsnorm", "out_proj"]
    phases = ["prefill", "decode"]
    key_cols = ["kernel", "batch", "seq_len", "context_len", "decode_steps", "model_dim", "num_heads"]
    dual_setups = [setup for setup in SETUP_ORDER if setup != "single_die"]

    fig, axes = plt.subplots(1, len(phases), figsize=(7 * len(phases), 5), constrained_layout=True)
    if len(phases) == 1:
        axes = [axes]

    width = 0.34
    for ax, phase in zip(axes, phases):
        phase_df = df[df["phase"] == phase].copy()
        if phase_df.empty:
            ax.set_visible(False)
            continue

        base = phase_df[phase_df["setup"] == "single_die"][key_cols + ["latency_ms_p50"]]
        if base.empty:
            ax.set_visible(False)
            continue

        x = np.arange(len(kernels))
        for idx, setup in enumerate(dual_setups):
            dual = phase_df[phase_df["setup"] == setup][key_cols + ["latency_ms_p50"]]
            if dual.empty:
                continue

            merged = dual.merge(base, on=key_cols, how="inner", suffixes=("_dual", "_single"))
            if merged.empty:
                continue

            merged["speedup"] = merged["latency_ms_p50_single"] / merged["latency_ms_p50_dual"]
            by_kernel = merged.groupby("kernel", as_index=False)["speedup"].median()
            y = []
            for kernel in kernels:
                row = by_kernel[by_kernel["kernel"] == kernel]
                y.append(float(row.iloc[0]["speedup"]) if not row.empty else np.nan)

            offset = (idx - (len(dual_setups) - 1) / 2.0) * width
            ax.bar(
                x + offset,
                y,
                width=width,
                color=COLORS[setup],
                label=_setup_label(setup),
            )

        ax.axhline(1.0, color="black", linestyle="--", linewidth=1)
        ax.set_xticks(x)
        ax.set_xticklabels(kernels, rotation=20, ha="right")
        ax.set_ylabel("single/dual latency ratio (p50)")
        ax.set_title(f"{phase} kernel speedup (>1 dual is faster)")
        ax.grid(axis="y", alpha=0.25)

    handles, labels = axes[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, ncols=2, loc="upper center", bbox_to_anchor=(0.5, 1.05))
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    args = parse_args()
    if not args.metrics_csv.exists():
        raise SystemExit(f"metrics.csv not found: {args.metrics_csv}")

    decode_slo_csv = args.decode_slo_csv or (args.metrics_csv.parent / "decode_slo_summary.csv")
    kernel_phase_csv = args.kernel_phase_csv or (args.metrics_csv.parent / "kernel_phase_metrics.csv")
    break_even_csv = args.break_even_csv or (args.metrics_csv.parent / "break_even_summary.csv")

    df = pd.read_csv(args.metrics_csv)
    slo_df = _safe_read_csv(decode_slo_csv)
    kernel_phase_df = _safe_read_csv(kernel_phase_csv)
    break_even_df = _safe_read_csv(break_even_csv)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    prefill_path = args.out_dir / f"{args.prefix}_prefill_latency.png"
    decode_path = args.out_dir / f"{args.prefix}_decode_throughput.png"
    slo_path = args.out_dir / f"{args.prefix}_decode_slo.png"
    kernel_phase_path = args.out_dir / f"{args.prefix}_kernel_phase_speedup.png"
    break_even_path = args.out_dir / f"{args.prefix}_break_even.png"

    _plot_prefill_latency(df=df, out_path=prefill_path)
    _plot_decode_throughput(df=df, out_path=decode_path)
    _plot_decode_slo(df=slo_df, out_path=slo_path)
    _plot_kernel_phase_speedup(df=kernel_phase_df, out_path=kernel_phase_path)
    _plot_break_even(df=break_even_df, out_path=break_even_path)

    print(prefill_path)
    print(decode_path)
    if not slo_df.empty:
        print(slo_path)
    if not kernel_phase_df.empty:
        print(kernel_phase_path)
    if not break_even_df.empty:
        print(break_even_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
